config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :stations do
    resources :reviews, except: :destroy
  end
  resources :votes, only: [:create]

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :stations, only: :destroy
    resources :reviews, only: :destroy
  end

  namespace :api do
    namespace :v1 do
      resources :votes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :station_id, presence: true

  belongs_to :station, optional: true
  has_many :votes, dependent: :destroy

  def vote_total
    total = 0
    votes.each do |vote|
      total += vote.value
    end
    total
  end
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, presence: true
  validates :line, presence: true
  validates :state, presence: true

  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :user_id, presence: true
  validates :review_id, presence: true
  validates :value, presence: true, inclusion: { in: -1..1 }
  belongs_to :user
  belongs_to :review

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:alert] = "Review deleted."
    redirect_to station_path(params[:station_id])
  end

end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:error] = "Station deleted from site"
    redirect_to root_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
    render :index
  end

  def destroy
    @users = User.all
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { render :index }
      format.json { render json: { data: "yooooo" } }
    end
  end
end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApplicationController
  protect_from_forgery with: :null_session

  def create

    @review = Review.find(vote_params[:review_id])
    @station = @review.station
    @vote = Vote.find_by(user_id: current_user.id, review_id: @review.id)
    user_input = vote_params[:value].to_i

    if @vote
      if @vote.value == 0
        @vote.value = user_input
        @vote.save
        render_json("Your vote has been updated!")
      else
        if @vote.value == user_input
          render_json("You can only vote once!")
        else
          @vote.value = 0
          @vote.save
          render_json("Your vote has been updated!")
        end
      end
    else
      @vote = Vote.create(user_id: current_user.id, review_id: vote_params[:review_id], value: vote_params[:value])
      render_json("Thanks for your vote!")
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:review_id, :value)
  end

  def render_json(message)
    render json: {
      voteTotal: @review.vote_total,
      voteMessage: message,
      reviewID: @review.id
    }, status: :created
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :admin])
  end

  def authenticate_admin!
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @stations = Station.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @station = Station.find(params[:station_id])
    @review = Review.find(params[:id])
  end

  def create
    @station = Station.find(params[:station_id])
    @review = Review.new(review_params)
    @review.station = @station

    if @review.save
      flash[:alert] = "Your comment has been successfully created!"
      redirect_to @station
    else
      flash[:error] = "Please provide both a title and a review"
      @reviews = @station.reviews
      render 'stations/show'
    end
  end

  def edit
    @review = Review.find(params[:id])
    @station = Station.find(params[:station_id])
    render :show
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      flash[:alert] = "Review successfully updated!"
      redirect_to station_review_path
    else
      flash[:alert] = "Please provide both a title and a review"
      @station = Station.find(params[:station_id])
      @review = Review.find(params[:id])
      render :show
    end
  end

  private
  def review_params
    params.require(:review).permit(:title, :content, :station_id)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    redirect_to root_path
  end

  def new
    @station = Station.new
  end

  def create

    @station = Station.new(station_params)

    if @station.save
      flash[:error] = "Your station has been successfully added!"
      redirect_to @station
    else
      flash[:error] = "Your station could not be created. Please provide all required information."
      render :new
    end
  end

  def show
    @station = Station.find(params[:id])
    @review = Review.new
    @reviews = @station.reviews
    @vote = Vote.new
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])

    if @station.update(station_params)
      flash[:error] = "Your station has been successfully updated!"
      redirect_to @station
    else
      flash[:error] = "Your station could not be updated. Please provide all required information."
      render :edit
    end
  end

  private

  def station_params
    params.require(:station).permit(:name, :line, :state, :description, :parking)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create

    @review = Review.find(vote_params[:review_id])
    @station = @review.station
    @vote = Vote.find_by(user_id: current_user.id, review_id: @review.id)
    user_input = vote_params[:value].to_i

    if @vote
      if @vote.value == 0

        @vote.value = user_input
        @vote.save
        flash[:alert] = "Your vote has been updated!"
        redirect_to @station
      else
        if @vote.value == user_input

          flash[:error] = "You can only vote once!"
          redirect_to @station
        else
          @vote.value = 0
          @vote.save

          flash[:alert] = "Your vote has been updated!"
          redirect_to @station
        end
      end
    else
      @vote = Vote.create(vote_params)

      flash[:alert] = "Thanks for your vote!"
      redirect_to @station
    end
  end

  private

  def vote
    @vote ||= Vote.find_by(user_id: vote[:user_id], review_id: vote[:review_id])
  end

  def vote_params
    params.require(:vote).permit(:user_id, :review_id, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.order(first_name: :desc).each do |user| %>

    <li id="user-<%= user.id %>"><%= user.first_name %> <%= user.last_name %> (<%= link_to "Delete User", admin_user_path(user), method: :delete, id: "user-delete-#{user.id}", class: "user-delete" %>)</li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h1>Metro Review Site</h1>

<% if @stations %>
  <ul>
    <% @stations.each do |station| %>
      <li><%= link_to "#{station.name} Station", station_path(station), id: "station-#{station.id}" %></li>
    <% end %>
  </ul>
<% end %>

<% if user_signed_in? %>
  <%= link_to "Add Station", new_station_path %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
  <% if current_user.admin? %>
    <li><%= link_to "View All Users", admin_users_path %></li>
  <% end %>
  <li><%= link_to 'Log Out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to 'Sign In', new_user_session_path %></li>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metro Review Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= yield %>
    <br />
    <div id="flash-container"></div>
    <% flash.each do |key, value|  %>
        <%= value %>
    <% end %>
  </body>
</html>

app/views/reviews/show.html.erb
<h1><%= @review.title %></h1>

<h3><%= @review.content %></h3>

<h1>Update Review</h1>

<%= form_for [@station, @review] do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :content, "Review" %>
  <%= f.text_area :content %>
  <br />
  <%= f.submit 'Update' %>
<% end %>

<% if user_signed_in? && current_user.admin? %>
  <h5><%= link_to "Delete Review", admin_review_path(@review, station_id: @station.id),  method: :delete %></h5>
<% end %>

<h5><%= link_to "Return to #{@station.name} Station", station_path(@station) %></h5>

app/views/stations/edit.html.erb
<h1>Update <%= @station.name %> Station</h1>

<%= form_for @station do |f| %>
  <%= f.label :name, "Station Name" %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :line %>
  <%= f.select :line, ['Blue', 'Orange', 'Silver', 'Green', 'Yellow', 'Red'] %>
  <br />
  <%= f.label :state %>
  <%= f.select :state, ['DC', 'Maryland', 'Virginia'] %>
  <br />
  <%= f.label :description %>
  <br />
  <%= f.text_area :description %>
  <br />
  <%= f.label :parking, "Parking?" %>
  <%= f.check_box :parking %>
  <br />
  <%= f.submit 'Update Station' %>

<% end %>

<% if current_user.admin? %>
  <%= link_to 'Delete Station', admin_station_path(@station), method: :delete, data: { confirm: "Are you sure you want to delete #{@station.name} Station?" } %>
<% end %>

app/views/stations/new.html.erb
<h1>Add Station</h1>

<%= form_for @station do |f| %>
  <%= f.label :name, "Station Name" %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :line %>
  <%= f.select :line, ['Blue', 'Orange', 'Silver', 'Green', 'Yellow', 'Red'] %>
  <br />
  <%= f.label :state %>
  <%= f.select :state, ['DC', 'Maryland', 'Virginia'] %>
  <br />
  <%= f.label :description %>
  <br />
  <%= f.text_area :description %>
  <br />
  <%= f.label :parking, "Parking?" %>
  <%= f.check_box :parking %>
  <br />
  <%= f.submit 'Add Station' %>

<% end %>

app/views/stations/show.html.erb
<h1><%= @station.name %> Station</h1>

<h3>Line: <%= @station.line %></h3>

<h3>State: <%= @station.state %></h3>

<h3>Description: <%= @station.description %></h3>

<h3>Parking? <% if @station.parking %> Yes <% else %> No <% end %> </h3>

<% if user_signed_in? %>
  <h1>Add Review</h1>

  <%= form_for [@station, @review] do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
    <br />
    <%= f.label :content, "Review" %>
    <%= f.text_area :content %>
    <br />
    <%= f.submit 'Submit Review' %>
  <% end %>
<% end %>

<h3>Reviews</h3>

<% @reviews.reverse.each do |review| %>
  <div class="review-title" ><%= link_to review.title, edit_station_review_path(@station, review) %>
    <% if user_signed_in? %>
      <div id="voting-buttons">
        <%= button_to "+", votes_path(Vote.new, params: { vote: { user_id: current_user.id, review_id: review.id, value: 1 } }), method: :post, id: "upvote-#{review.id}", class: "upvote" %>
        <%= button_to "-", votes_path(Vote.new, params: { vote: { user_id: current_user.id, review_id: review.id, value: -1 } }), method: :post, id: "downvote-#{review.id}", class: "downvote" %>
      </div>
    <% end %>

    <span class="vote-total" >User Rating:
      <span id="vote-total-<%= review.id %>" >
        <% if review.vote_total %>
          <%= review.vote_total %>
        <% else %>
          0
        <% end %>
      </span>
    </span>
    <% if !user_signed_in? %>
      (<%= link_to "Sign in to vote!", new_user_session_path %>)
    <% end %>
  </div>
  <div class="review-content" ><%= review.content %></div>
<% end %>


<% if user_signed_in? %>
  <%= link_to 'Update Station', edit_station_path(@station) %>
<% end %>